# Smart Intercom project
# https://github.com/Anonym-tsk/smart-domofon/tree/master/ge1mer

############# User configuration #############

substitutions:
  # Ge1mer board
  board: esp12e
  pin_relay_answer: GPIO14    # 330 Ohm, NO relay
  pin_relay_phone: GPIO16     # Intercom, NC relay
  pin_relay_mute: GPIO12      # 50 Ohm, NO relay
  pin_led_red: GPIO5
  pin_led_green: GPIO4
  pin_led_blue: GPIO15
  pin_call_detect: GPIO13
  pin_btn_accept: GPIO0

  # Board name
  board_name: "Domofon"
  mdns_name: "domofon"

  # Relays configuration
  phone_relay_inverted: 'true'  # Set to 'false' if you have NO phone relay

  # Wifi credentials
  wifi_ssid: "-----"
  wifi_password: ""
  ap_ssid: "Domofon"
  ap_password: "1234567890"

  # OTA and API
  ota_password: "esphome"
  api_password: "esphome"

  # Software configuration
  call_delay: 500ms     # Interval rings
  call_end_detect_delay: 5000ms     #  Interval between rings to detect incoming call
  relay_answer_on_time: 1000ms      # Delay between answer call and open/close door
  relay_open_on_time: 300ms         # How long the "open door button" will be pressed
  relay_after_open_delay: 500ms     # Delay in "answer" state after opening door
  short_click_time_from: 50ms       # Short button click min time
  short_click_time_to: 1000ms       # Long button click min time

  # Led configuration
  led_brightness: "0.7"

########### End user configuration ###########

packages:
  base: !include domofon_packages/base.yaml
  api: !include domofon_packages/api.yaml
#  mqtt: !include domofon_packages/mqtt.yaml
  script: !include domofon_packages/script.yaml
  output: !include domofon_packages/output.yaml
  switch: !include domofon_packages/switch.yaml
  light: !include domofon_packages/light.yaml
  binary_sensor: !include domofon_packages/binary_sensor.yaml
