esphome:
  name: $mdns_name
  platform: ESP8266
  board: $board
  comment: "https://github.com/Anonym-tsk/smart-domofon/tree/master/ge1mer"
  esp8266_restore_from_flash: true

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  fast_connect: on
  ap:
    ssid: $ap_ssid
    password: $ap_password

captive_portal:

web_server:

logger:
  baud_rate: 0
  logs:
    light: INFO

ota:
  password: $ota_password

# Blue status led
status_led:
  pin: $pin_led_blue

globals:
  - id: mode_auto_open
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: mode_auto_open_once
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: mode_auto_reject
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: mode_mute
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: mode_mute_once
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: incoming_call
    type: bool
    restore_value: no
    initial_value: 'false'
    
text_sensor:
  - platform: template
    name: "${board_name} Uptime"
    id: uptime_human
    icon: mdi:clock-start

sensor:
  - platform: template
    name: "${board_name} Heap Size"
    lambda: "return ESP.getFreeHeap();"
    update_interval: 20s
    unit_of_measurement: bytes
    accuracy_decimals: 0
    
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();
 
